docente/urls.py
from django.contrib import admin
from django.urls import path
from docente import views


app_name = "docente"
urlpatterns = [
    path('', views.docente_view, name='docente'),
    path('versiones/', views.versiones_view, name='versiones'),
    path('planificacion/', views.microcurricular_view, name="planificacion"),
    path('perfil/', views.perfildc_view, name='perfil'),
    path('configuracion/', views.configuraciondc_view, name='configuracion'),
    path('malla/<int:id>', views.malladc_view, name='malladc'),
    path('pdf/', views.vista_pdf, name='pdf'),
]

docente/models.py
from django.db import models

# Create your models here.

docente/views.py
from django.shortcuts import render, redirect
from processos.models import Asignatura


# Create your views here.
def docente_view(request):

    return render(request, 'dbs_docente.html',)


def versiones_view(request):
    objet_Asignatura = Asignatura.objects.filter(estado="A")
    if request.method == "POST":
        asignatura_id = int(request.POST["asignatura"])
        return redirect('docente:malladc', id=asignatura_id)
    return render(request, 'versiones.html', {'asignaturas': objet_Asignatura})


def microcurricular_view(request):

    objasignatura = Asignatura.objects.filter(estado="A")
    return render(request, 'microcurricular.html', {'asignatura': objasignatura})


def perfildc_view(request):
    return render(request, 'perfil_docente.html', {})


def configuraciondc_view(request):
    return render(request, 'configuraciondc.html', {})


def malladc_view(request, id):
    asignatura = Asignatura.objects.get(id=int(id), estado="A")
    return render(request, 'malladc.html', {
        'asignatura': asignatura
    })


def vista_pdf(request):
    return render(request, 'index.html', {})

docente/templates/configuraciondc.html
{% extends "dbs_docente.html" %}
{% block content %}
{% endblock content %}

docente/templates/dbs_docente.html
{% load static %}
<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>{% block title %}Inicio{% endblock %}</title>
    <!-- Favicon-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link href="{% static 'css/style2.css' %}" rel="stylesheet" />
</head>

<body>

    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light"><b>ISTG</b></div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'docente:planificacion' %}">Planificacion</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'docente:versiones' %}">Versiones</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="{% url 'docente:perfil' %}">Perfil</a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="#!">Estado</a>
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-primary" id="sidebarToggle">
                        <span class="navbar-toggler-icon"></span><!-- Esta clase representa el ícono de menú hamburguesa -->
                    </button>
                    <!-- Logo -->
                    <img src="{% static 'img/logo2.png' %}" style="max-width: 40%; height: auto;">
                    <!-- Navbar Collapse Button -->
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <!-- Navbar Links -->
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                            <li class="nav-item active"><a class="nav-link" href="{% url 'docente:docente' %}">Inicio</a></li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Usuario</a>
                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'docente:perfil' %}">Perfil</a>
                                    <a class="dropdown-item" href="{% url 'docente:configuracion' %}">Configuracion</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="{% url 'login' %}">Cerrar Sesion</a>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            {% block content %}
            <div class="container-fluid">
                <h1 class="mt-4"></h1>
                <div class="row align-items-md-stretch">
                    <div class="col-md-6">
                        <div class="h-100 p-5 text-bg-dark rounded-3">
                            <h2><b>Planificacion</b></h2>
                            <ul>
                                <li>
                                    <p>Malla Curricular</p>
                                </li>
                                <li>
                                    <p>Microcurrilar</p>
                                </li>
                            </ul>
                            <button class="btn btn-outline-light" type="button"><a
                                    href="#">Abrir</a></button>
                        </div>
                    </div>
                </div>
            </div>
            <div class="container-fluid">
                <h1 class="mt-4"></h1>
                <div class="row align-items-md-stretch">
                    <div class="col-md-6">
                        <div class="h-100 p-5 text-bg-dark rounded-3">
                            <h2><b>Versiones</b></h2>
                            <ul>
                                <li>
                                    <p>Malla Curricular (no editatble)</p>
                                </li>
                                <li>
                                    <p>Microcurricular 2022</p>
                                </li>
                                <li>
                                    <p>Microcurrilar 2023</p>
                                </li>
                            </ul>
                            <button class="btn btn-outline-light" type="button"><a
                                    href="{% url 'docente:versiones' %}">Abrir</a></button>
                        </div>
                    </div>
                </div>
            </div>
            {% endblock content %}
        </div>
    </div>


    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    {% load static %}
    <script src="{% static 'js/dashboard.js' %}"></script>
</body>

</html>

docente/templates/malladc.html
{% extends "dbs_docente.html" %}
{% block content %}

<div class="d-flex" id="wrapper">
    <div class="container-fluid">
        <h1 class="text-center">Versiones - {{ asignatura.nombre_asignatura }}</h1>
        <div class="row align-items-md-stretch">
            <div class="cardcol-md-6 w-100">
                <div class="p-5 text-bg-dark rounded-3 text-center">
                    <h1 class="text-ºcenter lead"></h1>
                    <br />
                    <table class="small table accordion table-bordered rounded">
                        <thead class="text-lg-center text-white" style="background-color: #274386">
                            <tr>
                                <th class="align-middle align-top">Nombre de version</th>
                                <th class="align-middle align-top">Fecha de creacion</th>
                                <th class="align-middle align-top">Responsable</th>
                                <th class="align-middle align-top">Acciones</th>
                        </thead>
                        <tbody class="texto-pequeño">
                            <td>microcurricular 2022</td>
                            <td>17/08/2022</td>
                            <td>Jordy Fajardo</td>
                            <td>
                                <div class="p-2">
                                    <button class="btn btn-success" type="button" class="btn btn-primary">
                                        <a href="{% url 'docente:pdf' %}">Abrir</a>
                                    </button>
                                    <button class="btn btn-primary" type="button" class="btn btn-primary"
                                        data-bs-toggle="modal" data-bs-target="#myModal">
                                        Editar
                                    </button>
                                    <button class="btn btn-danger" type="submit" name="eliminar">
                                        Eliminar Versio
                                    </button>
                                </div>
                            </td>

                        </tbody>
                    </table>
                    {% if msg %}
                    <div class="alert alert-success" role="alert">{{ msg }}</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

docente/templates/microcurricular.html
{% extends "dbs_docente.html" %}
{% block content %}
<div class="d-flex" id="wrapper">
    <div class="container-fluid">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
                <li class="breadcrumb-item">
                    <a class="link-body-emphasis" href="{% url 'docente:docente' %}">
                        <i class="material-icons">home</i>
                        <span class="visually-hidden"></span>
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a class="link-body-emphasis fw-semibold text-decoration-none" href="{% url 'docente:planificacion' %}">Planifiacion
                        Microcurricular</a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">
                    Registrar
                </li>
            </ol>
        </nav>
        <div class="row align-items-md-stretch">
            <h2 class="title" style="text-align: center;">Microcurriculares</h2>
            <div class="col-md-6 w-100">
        <div class="container">
            <!-- Inicio de la tabla -->
            <table class="table">
                <tr>
                    <!-- Primer elemento de la tabla -->
                    {% for i in asignatura %}
                        <td>
                            <div class="p-5 text-bg-dark rounded-3">
                                <h2 class="title" style="text-align: center;">{{ i.nombre_asignatura }}</h2>
                                <button class="btn btn-primary" type="button" style="background-color:#e5e5e5">
                                    <a href="#">Abrir</a>
                                </button>
                            </div>
                        </td>
                        <tr>
                    {% endfor %} 
            </table>
            <!-- Fin de la tabla -->
        </div>                
    </div>
</div>
{% endblock content %}

docente/templates/perfil_docente.html
{% extends "dbs_docente.html" %}
{% block content %}
{% endblock content %}

docente/templates/versiones.html
{% extends "dbs_docente.html" %} {% block content %}
<div class="d-flex" id="wrapper">
  <div class="container-fluid">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb p-3 bg-body-tertiary rounded-3">
        <li class="breadcrumb-item">
          <a class="link-body-emphasis" href="{% url 'docente:docente' %}">
            <i class="material-icons">home</i>
            <span class="visually-hidden"></span>
          </a>
        </li>
        <li class="breadcrumb-item">
          <a
            class="link-body-emphasis fw-semibold text-decoration-none"
            href="{% url 'docente:versiones' %}"
            >Versiones</a
          >
        </li>
        <li class="breadcrumb-item active" aria-current="page">Registrar</li>
      </ol>
    </nav>
    <div class="row align-items-md-stretch">
      <div class="d-flex" id="wrapper">
        <div class="container-fluid">
          <div class="row align-items-md-stretch">
            <div class="col-md-6 w-100">
              <div class="p-5 text-bg-dark rounded-3">
                <h2 class="title" style="text-align: center">
                  Historial de versiones
                </h2>
                <br />
                <form method="post">
                  {% csrf_token %}
                  <label for="asignatura"
                    >Seleccione version de una asignatura:</label
                  >
                  <select
                    class="form-select"
                    name="asignatura"
                    id="asignatura"
                    ria-label="Default select example"
                  >
                    <option selected>Selecione el periodo</option>
                    {% for asignatura in asignaturas %}
                    <option value="{{ asignatura.id }}">
                      {{ asignatura.nombre_asignatura }}
                    </option>
                    {% endfor %}</select
                  ><br />
                  <button class="btn btn-primary" type="submit">
                    Seleccionar
                  </button>
                </form>
                {% if msg %}
                <div class="alert alert-success" role="alert">{{ msg }}</div>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!--<script>
  // Función para mostrar los cambios en el cuadro de "cambios"
  function mostrarCambios(cambio) {
    var cambiosDiv = document.getElementById("cambios");
    cambiosDiv.innerHTML += "<p>" + cambio + "</p>";
  }

  // Función que se ejecutará cada vez que haya un cambio en la página
  function registrarCambio(evento) {
    var cambio = evento.target.tagName + " " + evento.target.id + " ha sido modificado.";
    mostrarCambios(cambio);
  }

  // Agregar un eventListener a todos los elementos de la página
  var elementos = document.getElementsByTagName("*");
  for (var i = 0; i < elementos.length; i++) {
    elementos[i].addEventListener("change", registrarCambio);
  }
</script>-->
{% endblock content %}